"""Added signatories

Revision ID: 01c4c08634d6
Revises: 74be4fd2f8c7
Create Date: 2024-05-28 15:51:46.616897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c4c08634d6'
down_revision = '74be4fd2f8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signatories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transaction_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('signatory_id', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.Boolean(), nullable=True),
    sa.Column('approval_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signatory_id'], ['signatories.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('signatory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signatory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sig_name', sa.VARCHAR(), nullable=True),
    sa.Column('sig_email', sa.VARCHAR(), nullable=True),
    sa.Column('sig_phone', sa.VARCHAR(), nullable=True),
    sa.Column('sig_role', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('approved', sa.BOOLEAN(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transaction_approvals')
    op.drop_table('signatories')
    # ### end Alembic commands ###
