"""bank code

Revision ID: 0db19d53caf9
Revises: 958aeef9374d
Create Date: 2024-06-01 00:19:45.896100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db19d53caf9'
down_revision = '958aeef9374d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('bank_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'bank_code')
    # ### end Alembic commands ###
