"""added profile to organisation

Revision ID: 0fbfd1fe37b7
Revises: 986d578a3419
Create Date: 2024-05-14 13:42:50.752361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbfd1fe37b7'
down_revision = '986d578a3419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('orgType', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'orgType')
    # ### end Alembic commands ###
