"""Update Table Models

Revision ID: 653402bf4a3e
Revises: 2238067ef65b
Create Date: 2024-03-25 15:21:13.699037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653402bf4a3e'
down_revision = '2238067ef65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('banner', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'banner')
    # ### end Alembic commands ###
