"""Updated withdraw model

Revision ID: 6ccfca3d6811
Revises: 653402bf4a3e
Create Date: 2024-03-25 16:33:52.763465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccfca3d6811'
down_revision = '653402bf4a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
