"""Added signatories

Revision ID: 74be4fd2f8c7
Revises: 6d6dceda0c6e
Create Date: 2024-05-28 15:02:25.203398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74be4fd2f8c7'
down_revision = '6d6dceda0c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signatory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sig_name', sa.String(), nullable=True),
    sa.Column('sig_email', sa.String(), nullable=True),
    sa.Column('sig_phone', sa.String(), nullable=True),
    sa.Column('sig_role', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signatory')
    # ### end Alembic commands ###
