"""added pin to accounts

Revision ID: 7cd252485f18
Revises: 9f95e09a2b68
Create Date: 2024-04-09 20:27:12.344705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd252485f18'
down_revision = '9f95e09a2b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('pin', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'pin')
    # ### end Alembic commands ###
