"""Transaction table enhanced

Revision ID: 7fbd3b9a7a4b
Revises: 733d371ba372
Create Date: 2024-04-25 18:51:53.096864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbd3b9a7a4b'
down_revision = '733d371ba372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('batch_status', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('trans_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('trans_status', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_account_no', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('campaign_name', sa.String(), nullable=True))
    op.drop_column('transactions', 'transaction_account')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'wallet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('wallet_id', sa.VARCHAR(), nullable=True))
    op.add_column('transactions', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_account', sa.VARCHAR(), nullable=True))
    op.drop_column('transactions', 'campaign_name')
    op.drop_column('transactions', 'transaction_account_no')
    op.drop_column('transactions', 'trans_status')
    op.drop_column('transactions', 'trans_type')
    op.drop_column('transactions', 'batch_status')
    # ### end Alembic commands ###
