"""new table

Revision ID: 8c2426bfa133
Revises: eeb8f8df3f7b
Create Date: 2024-05-31 19:28:40.876295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2426bfa133'
down_revision = 'eeb8f8df3f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('acc_refence', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('narrative', sa.String(), nullable=True))
        batch_op.drop_column('org_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('narrative')
        batch_op.drop_column('acc_refence')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
