"""added org id to transactions

Revision ID: 902cd82fbc80
Revises: 7fbd3b9a7a4b
Create Date: 2024-04-26 13:32:40.616453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902cd82fbc80'
down_revision = '7fbd3b9a7a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('org_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'org_id')
    # ### end Alembic commands ###
