"""added profile to organisation

Revision ID: 986d578a3419
Revises: f9357d53a793
Create Date: 2024-05-14 13:40:28.889221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986d578a3419'
down_revision = 'f9357d53a793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('profileImage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'profileImage')
    # ### end Alembic commands ###
