"""bank code

Revision ID: a5b135bb9e61
Revises: 0db19d53caf9
Create Date: 2024-06-01 01:12:19.031505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b135bb9e61'
down_revision = '0db19d53caf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('bank_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'bank_code')
    # ### end Alembic commands ###
