"""Added links and method

Revision ID: cdbeb0047899
Revises: e31b527faee5
Create Date: 2024-05-16 21:36:19.675196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbeb0047899'
down_revision = 'e31b527faee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('method', sa.String(), nullable=False))
    op.add_column('organisations', sa.Column('website_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'website_link')
    op.drop_column('donations', 'method')
    # ### end Alembic commands ###
