"""Invoice column in the Donation

Revision ID: ce7f6a976948
Revises: d53d98582e64
Create Date: 2024-04-06 15:59:40.622067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7f6a976948'
down_revision = 'd53d98582e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('invoice_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'invoice_id')
    # ### end Alembic commands ###
