"""donation status field updated

Revision ID: d53d98582e64
Revises: ba4821c0d1e1
Create Date: 2024-04-06 13:01:01.570228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53d98582e64'
down_revision = 'ba4821c0d1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'status')
    # ### end Alembic commands ###
