"""added donor name

Revision ID: d7c73597ad95
Revises: 902cd82fbc80
Create Date: 2024-05-04 13:37:47.234975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c73597ad95'
down_revision = '902cd82fbc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('donor_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'donor_name')
    # ### end Alembic commands ###
