"""changed data type

Revision ID: df7b2bfdeede
Revises: a5b135bb9e61
Create Date: 2024-06-18 13:13:01.093415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7b2bfdeede'
down_revision = 'a5b135bb9e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
