"""added youtube links

Revision ID: f9357d53a793
Revises: 667f21451866
Create Date: 2024-05-10 12:43:42.321033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9357d53a793'
down_revision = '667f21451866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_links')
    op.add_column('campaigns', sa.Column('youtube_link', sa.String(), nullable=True))
    op.add_column('organisations', sa.Column('youtube_link', sa.String(), nullable=True))
    op.drop_column('organisations', 'org_pin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('org_pin', sa.VARCHAR(), nullable=True))
    op.drop_column('organisations', 'youtube_link')
    op.drop_column('campaigns', 'youtube_link')
    op.create_table('youtube_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('link', sa.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
